### ISSUE TITLE
Can't install with PHP 8

### ISSUE THREAD

**Issue by jimblue** [WyriHaximus/HtmlCompress#114]
Hello,

I'm using HTMLCompress in a lib and tried to upgrade to v4.1.0 to support PHP8.
When installing I'm having the following issue :

```bash
composer install
No lock file found. Updating dependencies instead of installing from lock file. Use composer update over composer install if you do not have a lock file.
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - wyrihaximus/js-compress 2.0.2 requires tedivm/jshrink ^1.3 -> satisfiable by tedivm/jshrink[v1.3.0, v1.3.1, v1.3.2, v1.3.3].
    - jimblue/htmlmin 1.0.0 requires php ^7.4 -> your php version (8.0.0) does not satisfy that requirement.
    - wyrihaximus/html-compress 4.0.0 requires php ^7.4 -> your php version (8.0.0) does not satisfy that requirement.
    - tedivm/jshrink[v1.3.0, ..., v1.3.3] require php ^5.6|^7.0 -> your php version (8.0.0) does not satisfy that requirement.
    - wyrihaximus/js-compress 2.0.1 requires php ^7.2 -> your php version (8.0.0) does not satisfy that requirement.
    - jimblue/htmlmin 1.1.0 requires wyrihaximus/html-compress ^4.0 -> satisfiable by wyrihaximus/html-compress[4.0.0, 4.1.0].
    - wyrihaximus/html-compress 4.1.0 requires wyrihaximus/js-compress ^2.0.1 -> satisfiable by wyrihaximus/js-compress[2.0.1, 2.0.2].
    - Root composer.json requires jimblue/htmlmin ^1.0 -> satisfiable by jimblue/htmlmin[1.0.0, 1.1.0].
```

**Comment by WyriHaximus** [comment]
Hah I thought I had addressed everything in the dependency chain. But it turns out `jshrink` isn't yet. There is this PR https://github.com/tedious/JShrink/pull/97 that got merged, and it looks like my main issue with it has also been resolved https://github.com/tedious/JShrink/issues/96.

Just opened https://github.com/tedious/JShrink/issues/100 and hopefully, there will be a new release soon. Alternatively I have to drop it and release a new major version until it's resolved.

**Comment by jimblue** [comment]
Thank for your message @WyriHaximus 
Hopefully  *JShrink* release with PHP 8 support will be out soon enough🤞🏼 🤞🏼 🤞🏼

**Comment by WyriHaximus** [comment]
No problem @jimblue, if next weekend nothing has happened I'll go the new major version route.

**Comment by jimblue** [comment]
Hi @WyriHaximus, just a friendly ping 😄

**Comment by WyriHaximus** [comment]
Well it's next weekend now @jimblue, I'll do a double major release tonight for the JS compress. One removing `jshrink` and another one adding `jshrink` again right after.

**Comment by WyriHaximus** [comment]
@jimblue try now

**Comment by jimblue** [comment]
fixed ! thank you so much @WyriHaximus you rock 💥 🎸

**Comment by WyriHaximus** [comment]
@jimblue cheers, will keep an eye on jshrink for include it again once it's fixed
