### ISSUE TITLE
HtmlCompressor: Whitespace should be condensed, not removed

### ISSUE THREAD

**Issue by nochso** [WyriHaximus/HtmlCompress#14]
This will currently swallow the \r and/or \n
```html
<p>This is written as
multiple lines</p>
```

However it should be treating \r \n and \t as whitespace:
```html
<p>This is written as multiple lines</p>
```

See: http://stackoverflow.com/questions/588356/why-does-the-browser-renders-a-newline-as-space

**Comment by WyriHaximus** [comment]
You're absolutely right, thank you for the PR, I've tagged `1.0.1` with your fix :+1:

**Comment by nochso** [comment]
My pleasure :)
