### ISSUE TITLE
Please re-introduce externalCompressors flag on Factory::constructSmallest() or tidy up dependencies downstream.

### ISSUE THREAD

**Issue by Basster** [WyriHaximus/HtmlCompress#149]
In 520e7cec677bb44248a0de8033b217d93b37dc56 you've removed the `$externalCompressors` flag on `Factory::constructSmallest()`. 

Unfortunately both dependent factories CssCompress -> Factory and JsCompress -> Factory still have this flag (default: `true`) and both now load the `YUI\Compressor` which has a very questionable processing and exception handling:

Deep down in [`YUI\Compressor`](https://github.com/Jalle19/php-yui-compressor/blob/master/lib/YUI/Compressor.php#L126) it performs a `proc_open` on the required `yuicompressor.jar` (which is present, because of composer requirement in `nervo/yuicompressor`) but fails on the corresponding `fwrite` throwing an exception but leaving the `proc_open` pointer open (no exception handling with proc_close) which may lead to a lot of unnecessary process handlers.

**Comment by WyriHaximus** [comment]
Doh, will tidy up the dependencies, this was never intended to happen. Sorry about that :(

**Comment by WyriHaximus** [comment]
Ok, I found where this went wrong. At which point I completely forgot to drop the YUI compressors in dependencies and as such messed up. Working on PR's for both now resolve that and fix that in here as well

**Comment by WyriHaximus** [comment]
Just released [`4.1.3`](https://github.com/WyriHaximus/HtmlCompress/releases/tag/4.1.3) that drops the YUI compressors as I intended to do last year already.

**Comment by Basster** [comment]
Thank you @WyriHaximus!
