### ISSUE TITLE
Composer warning

### ISSUE THREAD

**Issue by jimblue** [WyriHaximus/HtmlCompress#155]
Hello,

First thank you for your amazing package, loving it :)

It's absolutely not urgent or breaking, but just to let you know that I've seen the following Composer warning while installing **HtmlCompress**:

```bash
Generating optimized autoload files
Warning: Ambiguous class resolution, "WyriHaximus\Compress\CompressorInterface" was found 2x: in "/Users/jim/Development/websites/immersion-pictures/vendor/wyrihaximus/compress/src/CompressorInterface.php" and "/Users/jim/Development/websites/immersion-pictures/vendor/wyrihaximus/compress-contracts/src/CompressorInterface.php", the first will be used.
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
```

All the best

**Comment by WyriHaximus** [comment]
Hey @jimblue, let me have a look as that shouldn't be happening.

**Comment by WyriHaximus** [comment]
Found the issue :tada:

**Comment by WyriHaximus** [comment]
Just tagged [`4.2.0`](https://github.com/WyriHaximus/HtmlCompress/releases/tag/4.2.0) that should resolve this issue for you

**Comment by jimblue** [comment]
Fixed 🎉 awesome @WyriHaximus thank you so much for you help :)

**Comment by WyriHaximus** [comment]
You're welcome 👍 !
