### ISSUE TITLE
Cannot assign null to property DOMElement::$id of type string

### ISSUE THREAD

**Issue by JoomBall** [WyriHaximus/HtmlCompress#168]
This library always gone very well to minimize HTML, but when updating PHP 8.3 I get this error: Cannot assign null to property DOMElement::$id of type string.

Any suggestion that may be happening? thank you so much

![ERROR-HTMLCOMPRESSOR](https://github.com/WyriHaximus/HtmlCompress/assets/16047586/fd80db28-7f18-4863-9ae0-f023bd05c3f4)

**Comment by ani2life** [comment]
This issue is with the voku/simple_html_dom package that this package uses.
The bug has been known since last December, and a PR has been submitted, but a new version has yet to be released.
https://github.com/voku/HtmlMin/issues/93

**Comment by JoomBall** [comment]
Thanks for the response, I see that they haven't released a new version in more than a year.
Let's hope they update soon and continue with the project or we will have to find another alternative.

**Comment by WyriHaximus** [comment]
Just did #174 from my end to support PHP 8.3. But will have to wait for @voku's release before I will tag a new release with PHP 8.2+ support as it doesn't make sense without it. Also subscribed to https://github.com/voku/HtmlMin/issues/93 to keep myself in the loop on this issue.

**Comment by Brenneisen** [comment]
@WyriHaximus With the latest tags from https://github.com/voku/simple_html_dom/releases/tag/4.8.9 and https://github.com/voku/HtmlMin/releases/tag/4.5.1 the problem should be solved. The issues are still open but the fix is already merged and released: https://github.com/voku/simple_html_dom/pull/106. Is it possible to have a release here soon? Thank you!

**Comment by WyriHaximus** [comment]
@Brenneisen Will get a release out this weekend, not sure why Renovate isn't picking up the new releases weirdly enough

**Comment by JoomBall** [comment]
For me personally it has been working perfectly for more than a week, without giving any errors with PHP 8.3. after the last [https://github.com/voku/simple_html_dom/releases/tag/4.8.9](url) update and last [https://github.com/WyriHaximus/HtmlCompress/releases/tag/4.2.1](url).

**Comment by WyriHaximus** [comment]
Just tagged [`v4.3.0`](https://github.com/WyriHaximus/HtmlCompress/releases/tag/4.3.0), will do some other updates and fixes the coming days but this should fix the most pressing issue.
