### ISSUE TITLE
Add Twig extension to readme

### ISSUE THREAD

**Issue by nochso** [WyriHaximus/HtmlCompress#18]
I couldn't find a Twig extension so I made one: https://github.com/nochso/html-compress-twig

It's on Packagist now and comes with a Twig tag, function and filter. Feel free to add it to the README, maybe rename the heading to just "Integration".

**Comment by WyriHaximus** [comment]
Thanks added it :+1:

**Comment by nochso** [comment]
Awesome, thank you too.

I've been using your project while working on a benchmark utility: https://github.com/nochso/Benchmark/ Next up is being able to use custom results, e.g. compare compression ratio to compression speed.
Just thought you might be interested. Knowing me I'll end up with a new minifier while micro-optimizing pointlessly :)

**Comment by WyriHaximus** [comment]
Yeah I've seen it pass.

I'm open for PR's optimising the output even more 😀
