### ISSUE TITLE
Allow one space

### ISSUE THREAD

**Issue by cedvan** [WyriHaximus/HtmlCompress#23]
Hi,

it would be must to be able :

``` html
<ul> <ul>     =>     </ul> </ul>   # Keep because one space
```

``` html
<ul>  <ul>    =>     </ul></ul>   # Compress because more one space
```

Thank you for job ;)

**Comment by WyriHaximus** [comment]
Hey sorry for the late reply, been busy with https://github.com/reactphp/http/releases/tag/v0.8.0 the past few months. I'll be adding an edge case test for this later today/tomorrow ensuring this works as intended. Thank you for reporting, I'll keep you posted :+1:

**Comment by WyriHaximus** [comment]
This has been resolved for some time now so closing this issue
