### ISSUE TITLE
Not fully removing newlines with async/defer in script-tag

### ISSUE THREAD

**Issue by lifeofguenter** [WyriHaximus/HtmlCompress#26]
```
    <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&callback=initMap">
    </script>
```

(via: https://google-developers.appspot.com/maps/documentation/javascript/adding-a-google-map)

**Comment by WyriHaximus** [comment]
Interesting, I'll have a look at it. Thanks for reporting :+1:

**Comment by WyriHaximus** [comment]
Hey sorry for the late reply, been busy with https://github.com/reactphp/http/releases/tag/v0.8.0 the past few months. I'll be adding an edge case test for this later today/tomorrow ensuring this works as intended. Thank you for reporting, I'll keep you posted :+1:

**Comment by WyriHaximus** [comment]
After digging into this, this isn't a bug because the new line takes the same amount of space as a space. As demonstrated by the test in #30 and the fix in https://github.com/WyriHaximus/HtmlCompress/pull/30/commits/c89bd3711bc035a1907caf0dadf66e7153a14fcf

**Comment by WyriHaximus** [comment]
Just tagged [`1.3.0`](https://github.com/WyriHaximus/HtmlCompress/releases/tag/1.3.0) with this in it :tada: .
