### ISSUE TITLE
Whitespaces between tags should be replaced by one space, not zero.

### ISSUE THREAD

**Issue by gamag** [WyriHaximus/HtmlCompress#27]
Hi, thank you for your work.

To not change the semantics of the compressed document, any white space characters, (including line breaks) between tags should not be entirely removed, but replaced by a single space character. Is this somehow possible to achieve? 

(Sometimes, this spaces are quite annoying, but since removing them may break some layouts and is not compliant with normal HTML handling, removing them should be an extra step or at least a clearly documented feature. It's quite strange when a HTML-compressor is not "lossless" when looking at the rendered HTML.)

 PS: I think #23 is something slightly different, but related.

**Comment by jimblue** [comment]
@gamag... this will not minify properly... I already explain you!
Just add space inside tags not between two tags!

**Comment by jimblue** [comment]
HtmlCompress compress work like a charm...

**Comment by WyriHaximus** [comment]
Closing this as thing has been resolved ages ago
