### ISSUE TITLE
Details on the compression?

### ISSUE THREAD

**Issue by neuropass** [WyriHaximus/HtmlCompress#36]
Hi, @WyriHaximus 

I started using your plugin, however would you be so kind to provide some detailed info on what it does under the hood? Would be also easier to identify bugs if any this way.
For example does your plugin performs the following?

1-Remove HTML comments.
2-Remove slash in self closing elements. /> becomes >.
3-Remove type="text/css" and type="text/javascript" in style and script tags.
4-Minimize elements within . It will not keep any whitespace (except inside script).
5-Minimize elements within but keep spaces between tags to preserve inline data
6-Minimize inline SVG files (which are a bunch of XML tags).
7-Minimize Custom Elements. They look like this: My content.
8-Skip code, pre, script and textarea from being minified.

what about:
-remove CDATA tags?
-JSON support?

any options? for example what does it do for:
textarea, code, pre and script?

less ? more?
Thanks again in advance!

**Comment by WyriHaximus** [comment]
> Ok, sorry I had posted on the wrong repo that was from cackePHP.

No problem, was going to post here right after but things ran a difference course. Let me answer you in my next comment 😄 .

**Comment by WyriHaximus** [comment]
Anyway currently this packages partly supports the things you've listed. When I find time to work on v2 I want to build it up to be modular so you can plug in extra compressors your self. Or leaf certain ones out that cause issues for you. currently not sure how to handle that configuration wise. (Current version supports barely any configuration of that kind.) But it should IIRC leave textarea, code, and pre alone.

**Comment by WyriHaximus** [comment]
`2.0` is about to hit, after it's out I'll revamp the docs and add how to build up your own custom HTML compressor specifically to your needs.
