### ISSUE TITLE
json-ld is packed

### ISSUE THREAD

**Issue by nlemoine** [WyriHaximus/HtmlCompress#37]
My structured data in JSON-LD format is packed when applying compression and after a few tests, I can't tell why. 

Here is the `in.html` file I used to tun my tests, taken from edge cases test folder: https://www.dropbox.com/s/xhuxdprf62qrq40/in.html.zip?dl=1

**Comment by WyriHaximus** [comment]
PR is up at #38

**Comment by nlemoine** [comment]
👍 Thanks @WyriHaximus!

**Comment by nlemoine** [comment]
7.x
