### ISSUE TITLE
<style> tags trigger \RuntimeException when CSS is wrapped in HTML comment

### ISSUE THREAD

**Issue by kAlvaro** [WyriHaximus/HtmlCompress#62]
An HTML with code like this:

```html
<style><!--
h1 {
    color: red;
}
--></style>
```

... throws:

- Type: RuntimeException
- Message: Not valid HTML fragment! %3C%21--h1%7Bcolor%3Ared%7D
- File: [...]\vendor\voku\simple_html_dom\src\voku\helper\SimpleHtmlDom.php
- Line: 158

Removing HTML comments is a possible workaround:

```html
<style>
h1 {
    color: red;
}
</style>
```

This technique may not be fashionable any more but as far as I know it's still valid HTML.

**Comment by WyriHaximus** [comment]
Hmm good catch, had to look it up and it's still [allowed](https://www.w3.org/TR/html52/document-metadata.html#the-style-element). Also this is not something that could be easily fixed as it's something inside @voku's [simple HTML DOM package](https://github.com/voku/simple_html_dom).

**Comment by kAlvaro** [comment]
There're a lot of packages involved and I'm not familiar with any of them. But, after some debugging, I suspect it's really a bug in that other library, simple_html_dom. Perhaps I should report it to them.

The exception is thrown at `\voku\helper\SimpleHtmlDom::replaceChildWithString()` when fed with a fragment of (already compressed) CSS wrapped in an HTML comment from `\WyriHaximus\HtmlCompress\Pattern\Style::compress()`:

```php
// $compressedInnerHtml is like '<!--form{position:relative...}-->'
$element->innerhtml = $compressedInnerHtml; 
```

In e.g. JavaScript this seems totally correct:

```javascript
document.createElement("div").innerHTML = "<!--form{position:relative}-->"
```
This is the check that fails:

```php
$tmpDomString = $this->normalizeStringForComparision($newDocument);
$tmpStr = $this->normalizeStringForComparision($string);
if ($tmpDomString !== $tmpStr) {
    throw new \RuntimeException(
        'Not valid HTML fragment!' . "\n" .
        $tmpDomString . "\n" .
        $tmpStr
    );
}
```

`$tmpDomString` is a an empty string but `$tmpStr` is the URL-encoded version of our HTML comment :-?

**Comment by kAlvaro** [comment]
New finding: it fails because `$compressedInnerHtml` is missing the ending comment separator!

    <!-- h1{color:red}

**Comment by WyriHaximus** [comment]
Thanks for the updates, I'll add an edge case test for this and see if I can resolve it in this package or that this has to be fixed upstream

**Comment by WyriHaximus** [comment]
@kAlvaro #65 is up, tag should follow soon

**Comment by WyriHaximus** [comment]
[`2.0.1`](https://github.com/WyriHaximus/HtmlCompress/releases/tag/2.0.1) has been tagged
